# Generated by Django 4.0.4 on 2023-08-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, verbose_name='Token de Twitch')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('api', models.CharField(choices=[('comments', 'Comentarios'), ('streams', 'Streams'), ('viwers', 'Viwers')], max_length=100, verbose_name='API')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
