# Generated by Django 4.0.4 on 2023-08-09 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphantom',
            name='comment_res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_res', to='comments.comment', verbose_name='Comentario de respuesta de bot'),
        ),
    ]
