# Generated by Django 4.0.4 on 2023-08-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentphantom_comment_res'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentphantom',
            unique_together={('comment_mod', 'comment_res')},
        ),
    ]
