# Generated by Django 4.0.4 on 2023-08-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
