# Generated by Django 4.0.4 on 2023-08-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='api',
            field=models.CharField(choices=[('comments', 'Comentarios'), ('streams', 'Streams'), ('viwers', 'Viwers')], max_length=100, verbose_name='API'),
        ),
    ]
