# Generated by Django 4.0.4 on 2023-08-10 18:08

from django.db import migrations, models
import django.utils.timezone
import streams.models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_alter_stream_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='datetime',
        ),
        migrations.AddField(
            model_name='stream',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='stream',
            name='end_time',
            field=models.TimeField(default=streams.models.get_next_hour, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='stream',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio'),
        ),
    ]
