# Generated by Django 4.0.4 on 2023-08-10 18:37

from django.db import migrations, models
import streams.models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_remove_stream_datetime_stream_date_stream_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='date',
            field=models.DateField(default=streams.models.get_now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='end_time',
            field=models.TimeField(default=streams.models.get_now, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='start_time',
            field=models.TimeField(default=streams.models.get_now, verbose_name='Hora de inicio'),
        ),
    ]
