# Generated by Django 4.0.4 on 2023-08-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_alter_stream_date_alter_stream_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streams.streamer', verbose_name='Usuario de Twitch'),
            preserve_default=False,
        ),
    ]
