# Generated by Django 4.0.4 on 2023-08-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_alter_stream_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='access_token',
            field=models.CharField(default='', max_length=100, verbose_name='Token de acceso a Twitch'),
        ),
        migrations.AddField(
            model_name='streamer',
            name='refresh_token',
            field=models.CharField(default='', max_length=100, verbose_name='Token de actualización de Twitch'),
        ),
    ]
